### ISSUE TITLE
Info request: Can execution of the scripts be triggered by a scrape?

### ISSUE THREAD

**Issue by saulp** [gree-gorey/bash-exporter#3]
Hi,

First of all, thanks for sharing your code!

I have a question: The fact that an interval is defined in the exporter itself tells me that the scripts are possibly not triggered by a scrape... correct?

If so, is it possible to, optionally, have the scripts be executed on each scrape? This would allow for central config management... especially in cases such as ours, where the clients are inaccessible due to network topology, and we use PushProx to proxy the metrics.

Thanks!

**Comment by gree-gorey** [comment]
No, right now scripts cannot be triggered by scrape -- in order to do so exporter needs a lot of changes in the code.
And for me it doesn't seem to be a good idea for 2 reasons:
1. If you executing scripts on each request, your response time for a request becomes unpredictable or can be very long -- because script can take some time to execute and return results.
2. This can lead to DoS and overload of exporter: imagine that several clients simultaneously wants to scrape from this exporter and it would have to execute a lot of scripts for each of them on-the-fly.

If you really need this setup I would suggest to just write a simple http server in any language you prefer (Go, Python, Java) that listen for incoming requests, and for each of them executing bash scripts and returning simple strings like:
```
mymetric{mylabel="myvalue"} 3.14
mymetric2{mylabel="myvalue"} 2.71
```
It would be just 20 lines of code in Python
